name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: |
            .cache
            ~/.npm
          restore-keys: |
            mkdocs-material-
      - name: Download and patch mkdocs-material
        run: |
          # Download the latest mkdocs-material source
          git clone https://github.com/squidfunk/mkdocs-material
          cp material_browser_request9_4p.patch mkdocs-material/
          cd mkdocs-material

          # Check if patch file exists
          if [ ! -f "material_browser_request9_4p.patch" ]; then
            echo "Error: Patch file not found!"
            exit 1
          fi

          # Apply your patch file
          echo "Applying patch..."
          patch -p 0 < material_browser_request9_4p.patch

          # Verify patch was applied successfully
          echo "Patch applied successfully!"

          # Install npm dependencies
          npm install
          
          # Build the frontend assets
          npm run build
          
          # Install the patched version
          pip install -e .

      - run: pip install mkdocs-encryptcontent-plugin
      - run: mkdocs gh-deploy --force